services:
  vue_site1:
    build: ./vue-hello-world
    networks:
      - nginx_network
    volumes:
      - ./dist:/app/dist
    command: npm run build
  #    ports:
  #      - "8080:8080"

  nginx_vue_site1:
    image: nginx:latest
    container_name: ${NGINX_CONTAINER_NAME}
    networks:
      - nginx_network
    env_file:
      - .env
    depends_on:
      - vue_site1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html

networks:
  nginx_network:
    name: ${NGINX_NETWORK_NAME}
    external: true